AugustinasJarockis/OMGVA-PoS

- OMGVA PoS.sln
- Unit tests/GlobalUsings.cs
- Unit tests/TestTests.cs
- Unit tests/Unit tests.csproj
Add a unit test project with some basic dependencies and basic test examples.
> Add unit test project

- OMGVA PoS/appsettings.json
Deleted this for safety reasons. Newly generated SecretKey will be send to contributors.
> Deleting JWT from appsettings.json

- OMGVA PoS/Business layer/Controllers/UserController.cs
- OMGVA PoS/Helper modules/Utilities/StringFormatValidators.cs
- Tests/Unit tests/StringFormatValidatorTests.cs
With this PR I:
- fixed regexes for usernames, passwords and names
- uncommented tests for rest of the string validations
- changed user controller's route to be "user" instead of "User" to better match the documentation
> Validations fix

- OMGVA PoS/ClientApp/src/components/LoginForm/index.tsx
- OMGVA PoS/ClientApp/src/pages/LoginPage.tsx
> Minor front changes - login form

- OmgvaPOS/Program.cs
- OmgvaPOS/src/BusinessManagement/Controller/BusinessController.cs
- OmgvaPOS/src/BusinessManagement/Mappers/BusinessMappers.cs
- OmgvaPOS/src/BusinessManagement/Repository/BusinessRepository.cs
- OmgvaPOS/src/BusinessManagement/Repository/IBusinessRepository.cs
- OmgvaPOS/src/BusinessManagement/Services/BusinessService.cs
- OmgvaPOS/src/BusinessManagement/Services/IBusinessService.cs
Added service to business endpoints as well as mappers.
> Add business service

- OmgvaPOS/ClientApp/src/App.tsx
- OmgvaPOS/ClientApp/src/components/Forms/LoginForm/index.tsx
- OmgvaPOS/ClientApp/src/components/Forms/TaxDataForm/index.tsx
- OmgvaPOS/ClientApp/src/pages/Business pages/BusinessPage.tsx
- OmgvaPOS/ClientApp/src/pages/Business pages/CreateBusinessPage.tsx
- OmgvaPOS/ClientApp/src/pages/GiftcardPage/GiftcardListPage.tsx
- OmgvaPOS/ClientApp/src/pages/Tax pages/CreateTaxPage.tsx
- OmgvaPOS/ClientApp/src/pages/Tax pages/TaxListPage.tsx
- OmgvaPOS/ClientApp/src/services/authService.ts
- OmgvaPOS/ClientApp/src/services/taxService.ts
- OmgvaPOS/Program.cs
Fixed frontend properties casing and other minor issues.
> Fix frontend properties

- OmgvaPOS/src/ItemManagement/Services/IItemService.cs
- OmgvaPOS/src/ItemManagement/Services/ItemService.cs
- OmgvaPOS/src/OrderItemManagement/Controller/OrderItemController.cs
- OmgvaPOS/src/OrderItemManagement/Mappers/OrderItemMapper.cs
- OmgvaPOS/src/OrderItemManagement/Repository/IOrderItemRepository.cs
- OmgvaPOS/src/OrderItemManagement/Repository/OrderItemRepository.cs
- OmgvaPOS/src/OrderItemManagement/Service/IOrderItemService.cs
- OmgvaPOS/src/OrderItemManagement/Service/OrderItemService.cs
- OmgvaPOS/src/OrderManagement/DTOs/OrderDTO.cs
- OmgvaPOS/src/OrderManagement/DTOs/OrderItemTax.cs
- OmgvaPOS/src/OrderManagement/DTOs/SimpleDiscountDTO.cs
- OmgvaPOS/src/OrderManagement/DTOs/SimpleOrderDTO.cs
- OmgvaPOS/src/OrderManagement/DTOs/SimpleUserDTO.cs
- OmgvaPOS/src/OrderManagement/Mappers/OrderMapper.cs
- OmgvaPOS/src/OrderManagement/Repository/OrderRepository.cs
- OmgvaPOS/src/OrderManagement/Service/IOrderService.cs
- OmgvaPOS/src/OrderManagement/Service/OrderService.cs
- OmgvaPOS/src/OrderManagement/Validators/OrderValidator.cs
Changes:
- Order DTO now returns pretty much everything you would ever need related to that specific order
- additions and updations and such to OrderItems now return NoContent(), 
- From a frontend standpoint if an OrderItem is added or it's quantity is changed
- Another GET /order/{order-id} has to be sent to update the info.
- probably some other changes I don't remember
> Fixed OrderDTO, made some other key changes

- OmgvaPOS/src/ScheduleManagement/Models/EmployeeSchedule.cs
- OmgvaPOS/src/ScheduleManagement/Repository/ScheduleRepository.cs
Added JsonIgnor to avoid User being serialized when getting schedule data.
Minor refactor to use foreign User.
> Bug fix: Employee schedule navigational properties

- OmgvaPOS/ClientApp/src/pages/Tax pages/TaxListPage.tsx
- OmgvaPOS/src/ItemManagement/Services/ItemService.cs
Fix the bug with data reader, where update item repository method would crash when trying to update tax.
> Fix tax update

- OmgvaPOS/src/BusinessManagement/Mappers/BusinessMappers.cs
- OmgvaPOS/src/PaymentManagement/Controllers/PaymentController.cs
- OmgvaPOS/src/PaymentManagement/DTOs/PaymentDTO.cs
- OmgvaPOS/src/PaymentManagement/DTOs/PaymentRequest.cs
- OmgvaPOS/src/PaymentManagement/Mappers/PaymentMapper.cs
- OmgvaPOS/src/PaymentManagement/Services/IPaymentService.cs
- OmgvaPOS/src/PaymentManagement/Services/PaymentService.cs
Added these fixes:
- Made a mapper for conversions between DTO and Models
- Removed GetBusinessId from PaymentService and used BusinessService for that
- Added some error handling
- Added list of HTTP Status codes that each endpoint returns
> Payments fix comments

- OmgvaPOS/ClientApp/src/App.tsx
- OmgvaPOS/ClientApp/src/components/List/DeletableUpdatableReservationListItem.tsx
- OmgvaPOS/ClientApp/src/components/List/DeletableUpdatableScheduleListItem.tsx
- OmgvaPOS/ClientApp/src/components/Schedules/ScheduleViewer.css
- OmgvaPOS/ClientApp/src/components/Schedules/index.tsx
- OmgvaPOS/ClientApp/src/pages/Homepage.tsx
- OmgvaPOS/ClientApp/src/pages/Reservation pages/ReservationCreatePage.tsx
- OmgvaPOS/ClientApp/src/pages/Reservation pages/ReservationUpdatePage.tsx
- OmgvaPOS/ClientApp/src/pages/Reservation pages/ReservationsListPage.tsx
- OmgvaPOS/ClientApp/src/pages/Schedule pages/CreateSchedulePage.tsx
- OmgvaPOS/ClientApp/src/pages/Schedule pages/EmployeeSchedulesPage.tsx
- OmgvaPOS/ClientApp/src/pages/Schedule pages/UpdateSchedulePage.tsx
- OmgvaPOS/ClientApp/src/services/reservationService.ts
- OmgvaPOS/ClientApp/src/services/scheduleService.ts
- OmgvaPOS/src/ScheduleManagement/Controller/ScheduleController.cs
- OmgvaPOS/src/ScheduleManagement/Service/IScheduleService.cs
- OmgvaPOS/src/ScheduleManagement/Service/ScheduleService.cs
Created a page to use in order flow. item id and employee id must be passed while navigating to this page.
> Employee schedules frontend

- OmgvaPOS/ClientApp/src/components/List/OrderItemListItem.tsx
- OmgvaPOS/ClientApp/src/pages/Order pages/OrderPages.css
- OmgvaPOS/src/OrderItemManagement/Service/OrderItemService.cs
> Fix bug in min amount

- OmgvaPOS/src/OrderManagement/Repository/OrderRepository.cs
On order creation, order now correctly returns user
> Fix user return on order creation

- OmgvaPOS/src/OrderItemManagement/Service/OrderItemService.cs
- OmgvaPOS/src/OrderManagement/Service/IOrderService.cs
- OmgvaPOS/src/OrderManagement/Service/OrderService.cs
Return full order from UpdateOrder
Fix MaxQuantity of orderItem
> Order fixes

- OmgvaPOS/ClientApp/src/components/List/DeletableUpdatableWithSchedulesListItem.css
- OmgvaPOS/ClientApp/src/components/List/DeletableUpdatableWithSchedulesListItem.tsx
- OmgvaPOS/ClientApp/src/pages/Business pages/BusinessPage.tsx
- OmgvaPOS/ClientApp/src/pages/Schedule pages/CreateSchedulePage.tsx
- OmgvaPOS/ClientApp/src/pages/Schedule pages/EmployeeSchedulesPage.tsx
- OmgvaPOS/ClientApp/src/pages/Schedule pages/UpdateSchedulePage.tsx
- OmgvaPOS/ClientApp/src/pages/UserPages/UserListPage.tsx
Schedules can be seen on user list for admin and owner.
> Token fixes and schedules 

- OmgvaPOS/src/ItemVariationManagement/Controller/ItemVariationController.cs
- OmgvaPOS/src/ItemVariationManagement/Services/ItemVariationService.cs
Fixes item variation controller TODOs and ensured proper validation of foreign keys.
> Fix item variation controller

- OmgvaPOS/ClientApp/src/App.tsx
- OmgvaPOS/ClientApp/src/pages/Homepage.tsx
- OmgvaPOS/ClientApp/src/pages/UserPages/UserDetailsPage.tsx
- Owner now can instantly see business page.
- Added user details page to employee.
> Bug fix: owner's page and user details page

- OmgvaPOS/ClientApp/src/components/List/OrderItemListItem.tsx
- OmgvaPOS/ClientApp/src/pages/Order pages/OrderItemSelectionCategoryPage.tsx
- OmgvaPOS/ClientApp/src/pages/Order pages/OrderItemSelectionPage.tsx
- OmgvaPOS/ClientApp/src/pages/Order pages/OrderPage.tsx
- OmgvaPOS/ClientApp/src/pages/Order pages/SelectOrderItemVariationsPage.tsx
- OmgvaPOS/ClientApp/src/pages/Reservation pages/ReservationCreatePage.tsx
- OmgvaPOS/ClientApp/src/services/orderService.ts
> Fix currencies

- OmgvaPOS/src/OrderItemManagement/Service/IOrderItemDeletionService.cs
- OmgvaPOS/src/OrderItemManagement/Service/OrderItemDeletionService.cs
- OmgvaPOS/src/OrderItemManagement/Service/OrderItemService.cs
- OmgvaPOS/src/OrderManagement/Controller/OrderController.cs
- OmgvaPOS/src/OrderManagement/Service/IOrderService.cs
- OmgvaPOS/src/OrderManagement/Service/OrderService.cs
- OmgvaPOS/src/OrderManagement/Validators/OrderValidator.cs
Created Endpoints:
- Cancel Order
- Refund Order
Also, updating order items, deleting order items, adding order items, no do not affect the InventoryQuantity of a service whatsoever
> Added Cancel Order and Refund Order

- OmgvaPOS/src/GiftcardManagement/Service/GiftcardService.cs
Giftcard update calculations have been modified so that when request has cents it does proper calculations (/100)
> Giftcard minor fixes

- OmgvaPOS/ClientApp/package-lock.json
- OmgvaPOS/ClientApp/src/pages/Reservation pages/ReservationCreatePage.tsx
- OmgvaPOS/ClientApp/src/services/reservationService.ts
- OmgvaPOS/OmgvaPOS.csproj
- OmgvaPOS/Program.cs
- OmgvaPOS/src/ReservationManagement/Controller/ReservationsController.cs
- OmgvaPOS/src/ReservationManagement/DTOs/CreateReservationRequest.cs
- OmgvaPOS/src/ReservationManagement/Service/ReservationService.cs
- OmgvaPOS/src/SmsManagement/SMSService.cs
Amazon SNS integration to send SMS
> Send SMS when creating a reservation

- OmgvaPOS/src/ReservationManagement/Service/ReservationService.cs
This PR should fix "create reservation" function to not let create a reservation if there is no available timeslot for selected date and time.
> Reservations - fixing schedule availability validation

- OmgvaPOS/ClientApp/src/pages/Order pages/OrderPage.tsx
- OmgvaPOS/src/PaymentManagement/Controllers/PaymentController.cs
Order goes to closed state when payment is successful
> Close order on payment success

- OmgvaPOS/ClientApp/src/components/Modals/PaymentModal.tsx
- OmgvaPOS/ClientApp/src/pages/Reservation pages/ReservationCreatePage.tsx
- OmgvaPOS/ClientApp/src/services/customerService.ts
Removed CustomerId and added CustomerName with which a new customer is being created
> New customer generation

- OmgvaPOS/ClientApp/src/components/Forms/OrderRefundDataForm/OrderRefundForm.css
- OmgvaPOS/ClientApp/src/components/Forms/OrderRefundDataForm/index.tsx
- OmgvaPOS/ClientApp/src/pages/Order pages/OrderPage.tsx
- OmgvaPOS/ClientApp/src/pages/Order pages/OrderPages.css
- OmgvaPOS/ClientApp/src/pages/Order pages/OrderRefundPage.tsx
- OmgvaPOS/Migrations/20241219122816_initial-create.Designer.cs
- OmgvaPOS/Migrations/20241219122816_initial-create.cs
- OmgvaPOS/src/Database/Context/OmgvaDbContext.cs
Fix various minor defect in the frontend.
> Minor fixes

- OmgvaPOS/src/OrderManagement/DTOs/GetOrdersRequestCriteria.cs
- OmgvaPOS/src/OrderManagement/Repository/OrderRepository.cs
> Adjust get orders endpoints ordering
